version: '3'

services:
  mysql-db:
    image: mysql:8.2.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: wkbloodbank
      MYSQL_DATABASE: wkbloodbank
      MYSQL_USER: wkbloodbank
      MYSQL_PASSWORD: wkbloodbank
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - wk_network
  
  wk-api:
    restart: on-failure:5
    build: ./wkbloodbank-api
    container_name: wk-api
    depends_on:
      - mysql-db
    networks:
      - wk_network
    environment:
      - DATABASE_URL=jdbc:mysql://mysql-db:3306/wkbloodbank?useSSL=false&allowPublicKeyRetrieval=true
      - DATABASE_USERNAME:wkbloodbank
      - DATABASE_PASSWORD:wkbloodbank
    ports:
      - 8080:8080
  
  wk-web:
    restart: on-failure:5
    container_name: wk-web
    build: "./wkbloodbank-frontend"
    ports:
      - 4200:4200

networks:
  wk_network:
    driver: bridge
