spring:
  servlet:
    multipart:
      max-file-size=50MB
      max-request-size=50MB
  datasource:
    url: jdbc:mysql://localhost:3306/wkbloodbank?useSSL=false&allowPublicKeyRetrieval=true
    username: wkbloodbank
    password: wkbloodbank
  jpa:
    hibernate:
      ddl-auto: update