spring:
  servlet:
    multipart:
      max-file-size=50MB
      max-request-size=50MB
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/wkbloodbank?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:wkbloodbank}
    password: ${DATABASE_PASSWORD:wkbloodbank}
  jpa:
    hibernate:
      ddl-auto: update